# Generated by Django 2.2.3 on 2019-08-07 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 12, 57, 19, 156245, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 7, 12, 57, 19, 156666, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
