# Generated by Django 2.2.3 on 2019-08-08 06:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20190807_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 6, 10, 14, 442330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 6, 10, 14, 442683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
