# Generated by Django 2.2.3 on 2019-08-08 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20190808_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 9, 23, 26, 483827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 9, 23, 26, 484183, tzinfo=utc)),
        ),
    ]
