# Generated by Django 2.2.3 on 2019-08-08 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20190808_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 9, 31, 45, 590621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 9, 31, 45, 590972, tzinfo=utc)),
        ),
    ]
