# Generated by Django 2.2.3 on 2019-08-08 09:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20190808_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 9, 48, 36, 56087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 8, 9, 48, 36, 55726, tzinfo=utc)),
        ),
    ]
