# Generated by Django 2.2.4 on 2019-08-09 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20190808_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 7, 20, 9, 535136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 7, 20, 9, 534778, tzinfo=utc)),
        ),
    ]
