# Generated by Django 2.2.4 on 2019-08-09 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20190809_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.Ingredients'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 10, 28, 29, 434183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 9, 10, 28, 29, 434519, tzinfo=utc)),
        ),
    ]
