# Generated by Django 2.2.3 on 2019-08-17 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20190809_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 11, 47, 8, 634029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 17, 11, 47, 8, 634460, tzinfo=utc)),
        ),
    ]
